apiVersion: batch/v1
kind: Job
metadata:
  name: kubernetes-job-example
  labels:
    jobgroup: jobexample
spec:
  template:
    metadata:
      name: kubejob
      labels:
        jobgroup: ansible-playbook
    spec:
      containers:
      - name: c
        image: quay.io/eslutsky/ansible:latest-tools
        env:
        - name: DEMO_GREETING
          value: "Hello from the environment"
        - name: DEMO_FAREWELL
          value: "Such a sweet sorrow"
        args: ["ansible-playbook"]
      restartPolicy: Never
